'\"
.\" Copyright (C) 2012-2015 RIKEN AICS
.\" nroff -u0 -Tlp -man
.TH kmrrungenscript.py 1 "2014-06-03" "KMR" "User Commands"
.SH NAME
kmrrungenscript.py \- generates a job-script
.SH SYNOPSIS
.LP
.nf
\fBkmrrungenscript.py\fR [-t rsctime] [-e node] [-s shape] [-p proc]
                   [-o outfile] [-d dir] [-O outdir] [-n task_proc]
                   -m mapper [-k kvgenerator] [-r reducer]
                   [-C] [-R ckptdir] [-S sched] [-w file] [-f]
.fi
.SH DESCRIPTION
.sp
.LP
kmrrungenscript.py generates a job-script for job schedulers.  It reads a
template of a job-script "kmrrungenscript.template" either from the
current directory, "lib" directory next to "bin" where this script is
found, or installation directory, searching in this order.  Currently,
it only supports "Parallelnavi" on K as a job scheduler.
.SH OPTIONS
.sp
.LP
The following options are supported:

.sp
.ne 2
.na
-t rsctime, --resource-time=rsctime
.ad
.sp .6
.RS 4n
Specifies time limit in the job resources.  This is given by
"00:00:00" format.
.RE

.sp
.ne 2
.na
-e node, --number-of-exec-node=node
.ad
.sp .6
.RS 4n
Specifies the number of nodes (processes) to execute.  Default is 1.
.RE

.sp
.ne 2
.na
-s shape, --shape=shape
.ad
.sp .6
.RS 4n
Specifies the MPI process shape.  Default is 1.
.RE

.sp
.ne 2
.na
-p procs, --proc=procs
.ad
.sp .6
.RS 4n
Specifies the number of MPI processes.  Default is 1.
.RE

.sp
.ne 2
.na
-o outfile, --outputfile=outfile
.ad
.sp .6
.RS 4n
Specifies the output file names.  Default is "output".
.RE

.sp
.ne 2
.na
-d indir, --inputdir=indir
.ad
.sp .6
.RS 4n
Specifies the input directory.  Default is "./input".
.RE

.sp
.ne 2
.na
-O outdir, --outputdir=outdir
.ad
.sp .6
.RS 4n
Specifies the output directory.  The output directory holds the result
files.  Default is the current directory.
.RE

.sp
.ne 2
.na
-n task_proc, --task-proc=task_proc
.ad
.sp .6
.RS 4n
Specifies the number of processes to run each mapper and reducer.
Default is 1.
.RE

.sp
.ne 2
.na
-m mapper, --mapper=mapper
.ad
.sp .6
.RS 4n
Specifies mapper program.
A mapper program can be a serial or an MPI program.
.RE

.sp
.ne 2
.na
-k kvgenerator, --kvgen=kvgenerator
.ad
.sp .6
.RS 4n
Specifies key-value generator program.
A key-value generator program should be a serial program.
.RE

.sp
.ne 2
.na
-r reducer, --reducer=reducer
.ad
.sp .6
.RS 4n
Specifies reducer program.
A reducer program can be a serial or an MPI program.
.RE

.sp
.ne 2
.na
-C, -ckpt
.ad
.sp .6
.RS 4n
Enables checkpoint/restart.
.RE

.sp
.ne 2
.na
-R ckptdir, --restart=ckptdir
.ad
.sp .6
.RS 4n
Specifies prefix of directories where checkpoint files are located.
.RE

.sp
.ne 2
.na
-S sched, --scheduler=sched
.ad
.sp .6
.RS 4n
Specifies a job scheduler.  Only "K" for Parallelnavi on K is
supported.
.RE

.sp
.ne 2
.na
-w scrfile, --write-scriptfile=scrfile
.ad
.sp .6
.RS 4n
Specifies a script output file.  Default is STDOUT.
.RE

.sp
.ne 2
.na
-f, --force
.ad
.sp .6
.RS 4n
Forces to create an output directory if it does not exist.
.RE


.SH EXAMPLES
.sp
.LP
For example, the following script is generated.
.sp
.nf
.RS
$ kmrrungenscript.py -e 10 -s 2 -p 2 -m pi.mapper -k pi.kvgen.sh \\
-r pi.reducer -f -C -R ckptdir_12345 -o 0.out
.sp
.nf
.RS -7
It will generate the following job script.
.sp
.nf
.RS
#!/bin/bash -x
#
#PJM --rsc-list "elapse=00:10:00"
#PJM --rsc-list "node=10"
#PJM --mpi "shape=2"
#PJM --mpi "proc=2"
#PJM --rsc-list "proc-core=unlimited"
#PJM --stg-transfiles "all"
#PJM --stgin "./kmrrun ./kmrrun"
#PJM --stgin "./pi.mapper ./pi.mapper"
#PJM --stgin "./pi.kvgen.sh ./pi.kvgen.sh"
#PJM --stgin "./pi.reducer ./pi.reducer"
#PJM --stgin "./work/* ./work/"
#PJM --stgin "./ckptdir_12345.00000/* ./ckptdir00000/"
#PJM --stgin "./ckptdir_12345.00001/* ./ckptdir00001/"
#PJM --stgin "./ckptdir_12345.00002/* ./ckptdir00002/"
#PJM --stgin "./ckptdir_12345.00003/* ./ckptdir00003/"
#PJM --stgout "./0.out ./"
#PJM --stgout "./ckptdir00000/* ./ckptdir_%j.00000/"
#PJM --stgout "./ckptdir00001/* ./ckptdir_%j.00001/"
#PJM --stgout "./core* ./"
#PJM -S

\&. /work/system/Env_base

mpirun -np 2 ./kmrrun -n 1 -m "./pi.mapper" -k "./pi.kvgen.sh" \\
-r "./pi.reducer" --ckpt ./work
.fi
.RE
