'\"
.\" Copyright (C) 2012-2016 RIKEN AICS
.\" nroff -u0 -Tlp -man
.TH kmrwatch0 1 "2014-02-04" "KMR" "User Commands"
.SH NAME
kmrwatch0 \- helps to launch processes by MPI spawn
.SH SYNOPSIS
.LP
.nf
\fBkmrwatch0\fR mpi \fIip-host-port\fR \fImagic\fR -- command and arguments...
.fi
.LP
.nf
\fBkmrwatch0\fR seq \fIany\fR \fImagic\fR -- command and arguments...
.fi
.SH DESCRIPTION
.sp
.LP
kmrwatch0 is used as a wrapper of command run by MPI_Comm_spawn().
.LP
The first synopsis...
.LP
The second synopsis...
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.na
None
.SH BUGS
